export const WORKSPACE_PACKAGES = [
  { folder: 'contracts', name: '@georesearch/dsh-contracts' },
  { folder: 'provider-lifecycle', name: '@georesearch/dsh-provider-lifecycle' },
  { folder: 'repository-providers', name: '@georesearch/dsh-repository-providers' },
  { folder: 'compatibility', name: '@georesearch/dsh-compat-rc5' },
  { folder: 'installation-guard', name: '@georesearch/dsh-installation-guard' },
  { folder: 'runtime-lease', name: '@georesearch/dsh-runtime-lease' },
  { folder: 'policy-service', name: '@georesearch/dsh-policy' },
  { folder: 'project-provider-files', name: '@georesearch/dsh-project-provider-files' },
  { folder: 'project-service', name: '@georesearch/dsh-project-service' },
  { folder: 'file-service', name: '@georesearch/dsh-file-service' },
  { folder: 'evidence-providers', name: '@georesearch/dsh-evidence-providers' },
  { folder: 'evidence-service', name: '@georesearch/dsh-evidence-service' },
  { folder: 'run-supervisor', name: '@georesearch/dsh-run-supervisor' },
  { folder: 'run-service', name: '@georesearch/dsh-run-service' },
  { folder: 'reproduction-service', name: '@georesearch/dsh-reproduction-service' },
  { folder: 'geospatial-provider-python', name: '@georesearch/dsh-geospatial-provider-python' },
  { folder: 'geospatial-service', name: '@georesearch/dsh-geospatial-service' },
  { folder: 'experiment-service', name: '@georesearch/dsh-experiment-service' },
  { folder: 'validation-service', name: '@georesearch/dsh-validation-service' },
  { folder: 'claim-service', name: '@georesearch/dsh-claim-service' },
  { folder: 'writing-service', name: '@georesearch/dsh-writing-service' },
  { folder: 'delegation-tools', name: '@georesearch/dsh-delegation-tools' },
  { folder: 'prompt', name: '@georesearch/dsh-prompt' },
  { folder: 'agent-lifecycle', name: '@georesearch/dsh-agent-lifecycle' },
  { folder: 'bundle', name: '@georesearch/dsh-bundle' },
  { folder: 'installer', name: '@georesearch/dsh-installer' },
] as const
